name: _
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - packages/prj_tktools
dependencies:
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_io
