name: tekartik_prj_tktools
description: Base prj tktools
version: 1.0.2
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  fs_shim: ">=2.4.0"
  args: ">=2.7.0"
  collection: ">=1.19.1" # not 1.19.0 as flutter 3.22 pins on 1.18
  cv: ">=1.1.10"
  dev_build: ">=1.1.2+11"
  path: ">=1.9.1"
  process_run: ">=1.2.4"
  source_span: ">=1.10.1"
  sembast: ">=3.8.5+1"
  cli_util: ">=0.4.2"
  tekartik_app_common_prefs:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_prefs
  tekartik_app_cv_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_cv_sembast
  tekartik_app_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_sembast
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  tekartik_pub:
    git:
      url: https://github.com/tekartik/pub.dart
  tekartik_sc:
    git:
      url: https://github.com/tekartik/sc.dart
  yaml: ">=3.1.3"
  yaml_edit: ">=2.2.2"
  tekartik_prefs:
    git:
      url: https://github.com/tekartik/prefs.dart
      path: prefs
  sqflite_common_ffi: ">=2.3.6"
  tekartik_app_crypto:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_crypto
  tekartik_mustache:
    git:
      url: https://github.com/tekartik/mustache.dart
      path: mustache
  tekartik_app_text:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_text
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_dev_menu
  http:
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_io
dev_dependencies:
  lints: ">=6.0.0"
  test: ">=1.26.3"
dependency_overrides:
  # tmp
  # sqlite3: ^2.9.4
  # sqflite_common_ffi: '>=2.3.6 <2.4.0'
resolution: workspace
#resolution: workspace
